os: linux
dist: xenial
language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - npm i git+https://github.com/jasmine/jasmine.git
  - npm i protractor
  - webdriver-manager update
  - webdriver-manager start
jobs:
  include:
    - stage: "Tests"
      name: "GUI Tests"
      script: protractor project/conf.js