os: linux
dist: xenial
language: node_js
node_js:
  - node
cache:
  timeout: 30 # default value is 3 minutes
  directories:
    - node_modules
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - npm i git+https://github.com/jasmine/jasmine.git
  - npm i protractor
  - webdriver-manager update
  - webdriver-manager start --detach
jobs:
  include:
    - stage: "Tests"
      name: "GUI Tests"
      script: protractor project/conf.js
after_script:
  - webdriver-manager shutdown