sudo: false
language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - npm install git+https://github.com/jasmine/jasmine.git